create extension if not exists pgcrypto;

do $$
begin
  create type public.platform_type as enum ('ps', 'xbox', 'nintendo', 'pc');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.role_type as enum ('dps', 'support', 'tank', 'flex');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.gamemode_type as enum ('6v6', '5v5');
exception
  when duplicate_object then null;
end $$;

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  name text not null default '',
  discord text not null default '',
  platform public.platform_type,
  role public.role_type,
  gamemode public.gamemode_type,
  bio text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint profiles_name_length check (char_length(name) <= 40),
  constraint profiles_discord_length check (char_length(discord) <= 40),
  constraint profiles_bio_length check (char_length(bio) <= 280)
);

create table if not exists public.heroes (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null unique,
  image_url text
);

create table if not exists public.profile_favorite_heroes (
  profile_id uuid not null references public.profiles (id) on delete cascade,
  hero_id bigint not null references public.heroes (id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  primary key (profile_id, hero_id)
);

create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  user_one_id uuid not null references public.profiles (id) on delete cascade,
  user_two_id uuid not null references public.profiles (id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint conversations_distinct_users check (user_one_id <> user_two_id)
);

create unique index if not exists conversations_unique_pair_idx
  on public.conversations (least(user_one_id, user_two_id), greatest(user_one_id, user_two_id));

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations (id) on delete cascade,
  sender_id uuid not null references public.profiles (id) on delete cascade,
  body text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint messages_body_length check (char_length(body) between 1 and 280)
);

create index if not exists messages_conversation_idx
  on public.messages (conversation_id, created_at);

create index if not exists messages_sender_idx
  on public.messages (conversation_id, sender_id);

create table if not exists public.blocks (
  id uuid primary key default gen_random_uuid(),
  blocker_id uuid not null references public.profiles (id) on delete cascade,
  blocked_id uuid not null references public.profiles (id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  constraint blocks_distinct_users check (blocker_id <> blocked_id),
  constraint blocks_unique_pair unique (blocker_id, blocked_id)
);

create or replace function public.is_blocked_between(user_a uuid, user_b uuid)
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.blocks
    where (blocker_id = user_a and blocked_id = user_b)
       or (blocker_id = user_b and blocked_id = user_a)
  );
$$;

create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id uuid not null references public.profiles (id) on delete cascade,
  reported_id uuid not null references public.profiles (id) on delete cascade,
  conversation_id uuid references public.conversations (id) on delete set null,
  details text not null,
  created_at timestamptz not null default timezone('utc', now()),
  constraint reports_distinct_users check (reporter_id <> reported_id),
  constraint reports_details_length check (char_length(details) between 1 and 500)
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id)
  values (new.id)
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.bump_conversation_activity()
returns trigger
language plpgsql
as $$
begin
  update public.conversations
  set updated_at = timezone('utc', now())
  where id = new.conversation_id;

  return new;
end;
$$;

drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at
before update on public.profiles
for each row execute procedure public.touch_updated_at();

drop trigger if exists conversations_touch_updated_at on public.conversations;
create trigger conversations_touch_updated_at
before update on public.conversations
for each row execute procedure public.touch_updated_at();

drop trigger if exists messages_touch_updated_at on public.messages;
create trigger messages_touch_updated_at
before update on public.messages
for each row execute procedure public.touch_updated_at();

drop trigger if exists bump_conversation_activity_trigger on public.messages;
create trigger bump_conversation_activity_trigger
after insert on public.messages
for each row execute procedure public.bump_conversation_activity();

alter table public.profiles enable row level security;
alter table public.heroes enable row level security;
alter table public.profile_favorite_heroes enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.blocks enable row level security;
alter table public.reports enable row level security;

drop policy if exists "profiles_select" on public.profiles;
create policy "profiles_select"
on public.profiles
for select
to authenticated
using (
  auth.uid() is not null
  and not public.is_blocked_between(auth.uid(), id)
);

drop policy if exists "profiles_insert" on public.profiles;
create policy "profiles_insert"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "profiles_update" on public.profiles;
create policy "profiles_update"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "heroes_select" on public.heroes;
create policy "heroes_select"
on public.heroes
for select
to authenticated
using (true);

drop policy if exists "favorite_heroes_select" on public.profile_favorite_heroes;
create policy "favorite_heroes_select"
on public.profile_favorite_heroes
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = profile_id
      and not public.is_blocked_between(auth.uid(), profiles.id)
  )
);

drop policy if exists "favorite_heroes_insert" on public.profile_favorite_heroes;
create policy "favorite_heroes_insert"
on public.profile_favorite_heroes
for insert
to authenticated
with check (auth.uid() = profile_id);

drop policy if exists "favorite_heroes_delete" on public.profile_favorite_heroes;
create policy "favorite_heroes_delete"
on public.profile_favorite_heroes
for delete
to authenticated
using (auth.uid() = profile_id);

drop policy if exists "conversations_select" on public.conversations;
create policy "conversations_select"
on public.conversations
for select
to authenticated
using (
  auth.uid() in (user_one_id, user_two_id)
  and not public.is_blocked_between(user_one_id, user_two_id)
);

drop policy if exists "conversations_insert" on public.conversations;
create policy "conversations_insert"
on public.conversations
for insert
to authenticated
with check (
  auth.uid() in (user_one_id, user_two_id)
  and user_one_id <> user_two_id
  and not public.is_blocked_between(user_one_id, user_two_id)
);

drop policy if exists "messages_select" on public.messages;
create policy "messages_select"
on public.messages
for select
to authenticated
using (
  exists (
    select 1
    from public.conversations
    where conversations.id = conversation_id
      and auth.uid() in (conversations.user_one_id, conversations.user_two_id)
      and not public.is_blocked_between(conversations.user_one_id, conversations.user_two_id)
  )
);

drop policy if exists "messages_insert" on public.messages;
create policy "messages_insert"
on public.messages
for insert
to authenticated
with check (
  sender_id = auth.uid()
  and exists (
    select 1
    from public.conversations
    where conversations.id = conversation_id
      and auth.uid() in (conversations.user_one_id, conversations.user_two_id)
      and not public.is_blocked_between(conversations.user_one_id, conversations.user_two_id)
  )
  and (
    select count(*)
    from public.messages as existing_messages
    where existing_messages.conversation_id = messages.conversation_id
      and existing_messages.sender_id = auth.uid()
  ) < 10
);

drop policy if exists "blocks_select" on public.blocks;
create policy "blocks_select"
on public.blocks
for select
to authenticated
using (auth.uid() = blocker_id);

drop policy if exists "blocks_insert" on public.blocks;
create policy "blocks_insert"
on public.blocks
for insert
to authenticated
with check (
  auth.uid() = blocker_id
  and blocker_id <> blocked_id
);

drop policy if exists "blocks_delete" on public.blocks;
create policy "blocks_delete"
on public.blocks
for delete
to authenticated
using (auth.uid() = blocker_id);

drop policy if exists "reports_select" on public.reports;
create policy "reports_select"
on public.reports
for select
to authenticated
using (auth.uid() = reporter_id);

drop policy if exists "reports_insert" on public.reports;
create policy "reports_insert"
on public.reports
for insert
to authenticated
with check (
  auth.uid() = reporter_id
  and reporter_id <> reported_id
);
